version: '3'

services:
  cadvisor:
    container_name: cadvisor
    build:
      context: .
      dockerfile: ./arm-cadvisor/Dockerfile
    network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro

  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter
    network_mode: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'